import './globals.css'
import "primeflex/primeflex.css";
import AppSidebar from '../components/sidebar/sidebar'
import 'primereact/resources/themes/lara-dark-blue/theme.css';
import AppNavbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer';

 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body   >
        <div  className='grid'>
            <div className=" col-12 " >
                <AppNavbar/>
            </div>
            <div className='grid flex  col-12 min-h-screen'>
                  
              <div className="col-2  ">
                  <AppSidebar></AppSidebar>
              </div>  
              <div className="col-10   bg-primary  ">
                {children}
              </div>
             {/* <div className='col-12 m-10 font-color-black bg-blue '>
                <Footer></Footer>
              </div>*/ }

       
            </div>
           
            
         
        </div>
      </body>
    </html>
  )
}
