import './globals.css'

import AppSidebar from '../components/sidebar/sidebar'

import AppNavbar from '@/components/navbar/navbar'

 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

    <body  className = "grid-container" >
       

          <div className ="header">
             <AppNavbar/>
          </div>
          <div className="contenu">

          </div>
     
           
       
     </body>
      
      
    </html>
  )
}
